#general:
#  kafka-topic: midas-transactions

spring:
  profiles:
    active: local
  datasource:
    url: ${MYSQL URI}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: ${DRIVER NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DIALECT URI}

  h2:
    console:
      enabled: false
  logging:
    level:
      root: INFO i have to change for h2

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_ID}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVER URI}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      auto-offset-reset: earliest
      group-id: ${GROUP_ID}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages:${PACKAGE_NAME}

    properties:
      sasl:
        mechanism: "PLAIN"
        jaas:
          config: ${KAFKA USERNAME AND PASSWORD}
      security:
        protocol: "SASL_SSL"
      session:
        timeout:
          ms: 45000
      client.id: ${CLIENT_ID}